version: '2'
services:
  mysql:
      image: mariadb
      environment:
        MYSQL_ROOT_PASSWORD: YOUR_ROOT_PASSWORD
        MYSQL_DATABASE: YOUR_DB_NAME
        MYSQL_USER: YOUR_DB_USER
        MYSQL_PASSWORD: YOUR_DB_PASSWORD
      volumes:
        - ./.data/mysql:/var/lib/mysql/data
  phpfpm:
    depends_on:
      - mysql
    image: my/phpfpm:latest
    build: ./docker/php-fpm
    volumes:
      - "./app:/var/www/html"
      - "./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini"
      - "./docker/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini"
    links:
      - mysql
      - mailcatcher
    restart: always
    extra_hosts:
      - "YOUR_DOMAIN:YOUR_DOCKER_IP" # Use the gateway address for your docker network for the ip address. This is so that PHP FPM can find nginx for the postback to do things like cron jobs with WordPress
  nginx:
    depends_on:
      - phpfpm
    ports:
      - "80:80"
    image: nginx:latest
    volumes:
      - "./app:/var/www/html"
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    links:
      - phpfpm
    restart: always
  mailcatcher:
      image: yappabe/mailcatcher
      ports:
          - 1025:1025
          - 1080:1080
